/** Legacy CSV filenames → current sequential names (split + renumber). */
export const CSV_LEVEL_RENAMES: Record<string, string> = {
  "01 Numbers.csv": "01 Numbers.csv",
  "01a Numbers.csv": "01 Numbers.csv",
  "01b Numbers.csv": "02 Numbers.csv",
  "02 Colours.csv": "03 Colours.csv",
  "02a Colours.csv": "03 Colours.csv",
  "02b Colours.csv": "04 Colours.csv",
  "03 To Be.csv": "05 To Be.csv",
  "04 Possessives - My.csv": "06 Possessives - My.csv",
  "05 Possessives - Your.csv": "07 Possessives - Your.csv",
  "06 Possessives - His Hers Ours.csv": "08 Possessives - His Hers Ours.csv",
  "07 Fruits and Vegetables.csv": "09 Fruits and Vegetables.csv",
  "08 More Adjectives.csv": "10 More Adjectives.csv",
  "09 Adjective and Noun.csv": "11 Adjective and Noun.csv",
  "10 Basic Verbs.csv": "12 Basic Verbs.csv",
  "11 Continuous Present 01.csv": "13 Continuous Present 01.csv",
  "12 Continuous Present 02.csv": "14 Continuous Present 02.csv",
  "13 Animals.csv": "15 Animals.csv",
  "14 Body Basics.csv": "16 Body Basics.csv",
  "15 Family.csv": "17 Family.csv",
  "16 Common Things.csv": "18 Common Things.csv",
  "17 Basic Adjectives.csv": "19 Basic Adjectives.csv",
  "18 Quick Replies.csv": "20 Quick Replies.csv",
  "19 Questions 01.csv": "21 Questions 01.csv",
  "20 Questions 02.csv": "22 Questions 02.csv",
  "21 Location.csv": "23 Location.csv",
  "22 Positions 01.csv": "24 Positions 01.csv",
  "23 Positions 02.csv": "25 Positions 02.csv",
  "24 With and To.csv": "26 With and To.csv",
  "25 Giving and Taking.csv": "27 Giving and Taking.csv",
  "26 States and Feelings.csv": "28 States and Feelings.csv",
  "27 Wants and Needs.csv": "29 Wants and Needs.csv",
  "28 In My Room - Present.csv": "30 In My Room - Present.csv",
  "29 In My Room - Imperatives.csv": "31 In My Room - Imperatives.csv",
  "30 In My Living Room - Present.csv": "32 In My Living Room - Present.csv",
  "31 In My Living Room - Imperatives.csv": "33 In My Living Room - Imperatives.csv",
  "32 In My Kitchen - Present.csv": "34 In My Kitchen - Present.csv",
  "33 In My Kitchen - Imperatives.csv": "35 In My Kitchen - Imperatives.csv",
  "34 In My Bathroom - Present.csv": "36 In My Bathroom - Present.csv",
  "35 In My Bathroom - Imperatives.csv": "37 In My Bathroom - Imperatives.csv",
  "36 Meals and Table Talk.csv": "38 Meals and Table Talk.csv",
  "37 At Home - Questions.csv": "39 At Home - Questions.csv",
  "38 Negatives - Imperatives.csv": "40 Negatives - Imperatives.csv",
  "39 Negatives - Present.csv": "41 Negatives - Present.csv",
  "40 Leaving and Arriving.csv": "42 Leaving and Arriving.csv",
  "41 Door and Errands.csv": "43 Door and Errands.csv",
  "42 Past - What I Did.csv": "44 Past - What I Did.csv",
  "43 Past - Questions.csv": "45 Past - Questions.csv",
  "44 Completed Actions - Gya.csv": "46 Completed Actions - Gya.csv",
  "45 Uses of Ho Gya.csv": "47 Uses of Ho Gya.csv",
  "46 Future - I Will.csv": "48 Future - I Will.csv",
  "47 Future - Questions.csv": "49 Future - Questions.csv",
  "48 Ke - And Then.csv": "50 Ke - And Then.csv",
  "49 People at Home - Mixed.csv": "51 People at Home - Mixed.csv",
  "50 Out and About - Mixed.csv": "52 Out and About - Mixed.csv",
  "51 Checking On People - Mixed.csv": "53 Checking On People - Mixed.csv",
  "52 Plans and Next - Mixed 01.csv": "54 Plans and Next - Mixed 01.csv",
  "53 Plans and Next - Mixed 02.csv": "55 Plans and Next - Mixed 02.csv",
  "54 Plans and Next - Mixed 03.csv": "56 Plans and Next - Mixed 03.csv",
  "55 Time Words.csv": "57 Time Words.csv",
  "56 Can and Can't.csv": "58 Can and Can't.csv",
  "57 Already and Not Yet.csv": "59 Already and Not Yet.csv",
  "58 At the Door.csv": "60 At the Door.csv",
  "59 Please and Thanks.csv": "61 Please and Thanks.csv",
  "60 Mere Kol.csv": "62 Mere Kol.csv",
  "61 How and Which.csv": "63 How and Which.csv",
  "62 Agar - If.csv": "64 Agar - If.csv",
  "63 Wants - Chahna.csv": "65 Wants - Chahna.csv",
  "64 Nature - Landscape.csv": "66 Nature - Landscape.csv",
  "65 Nature - Outdoors.csv": "67 Nature - Outdoors.csv",
  "66 Work - From Home.csv": "68 Work - From Home.csv",
  "67 Food and Place.csv": "69 Food and Place.csv",
  "68 London Transport.csv": "70 London Transport.csv",
  "69 Music - Playing.csv": "71 Music - Playing.csv",
  "70 Body - Head and Face.csv": "72 Body - Head and Face.csv",
  "71 Body - Arms Legs and Core.csv": "73 Body - Arms Legs and Core.csv",
  "72 Gym and Exercise.csv": "74 Gym and Exercise.csv",
  "73 Health - Wellness.csv": "75 Health - Wellness.csv",
  "74 Let's - Chalo.csv": "76 Let's - Chalo.csv",
  "75 Pasand - To Like.csv": "77 Pasand - To Like.csv",
  "76 Much and Many.csv": "78 Much and Many.csv",
  "77 Never and Always.csv": "79 Never and Always.csv",
  "78 Know and Don't Know.csv": "80 Know and Don't Know.csv",
  "79 I Think That.csv": "81 I Think That.csv",
  "80 Past To Be - Was and Were.csv": "82 Past To Be - Was and Were.csv",
  "81 Future To Be - Will Be.csv": "83 Future To Be - Will Be.csv",
  "82 Because and So.csv": "84 Because and So.csv",
  "83 Have To and Must.csv": "85 Have To and Must.csv",
  "84 Myself and Each Other.csv": "86 Myself and Each Other.csv",
  "85 Ago and Since.csv": "87 Ago and Since.csv",
  "86 Learning.csv": "88 Learning.csv",
  "87 Time Units.csv": "89 Time Units.csv",
};
